# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the OS, Python version, and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    pre_build:
      # Run sphinx-apidoc to auto-generate the .rst files
      # from the source code before the main build starts.
      - "sphinx-apidoc -o docs -e --force backpropcount/"

# Location of Sphinx configuration file
sphinx:
  configuration: docs/conf.py

# Python installation requirements.
python:
  install:
    # Install the documentation-specific dependencies.
    - requirements: docs/requirements.txt
